### ISSUE TITLE
the mptcp version

### ISSUE THREAD

**Issue by FaZoREX** [hoang-tranviet/mptcp-vagrant#2]
Hello,

I have installed this vagrantbox, it works perfectly. Now I want to install this mptcp kernel also directly on my computer, could you please give me the link to the mptcp kernel you used for this vagrantbox.

thank you in advance
Feri

**Comment by hoang-tranviet** [comment]
Hello @FaZoREX,

Sorry for my late response. Haven't seen your question before.

I use the MPTCP kernel 0.91.3 with socket API patches, you can find it here:
https://github.com/hoang-tranviet/mptcp/commits/mptcp_v0.91.3_api

Hoang

**Comment by FaZoREX** [comment]
thank you very much
